services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GENERIC_TIMEZONE
        value: Europe/Tashkent
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: otabek
      - key: N8N_BASIC_AUTH_PASSWORD
        value: strongpassword123
